### PR TITLE
Added Favicons

### PR DESCRIPTION
**Pull request by DanArthurGallagher**
I've added the icons and links for various favicons to the site.

I followed the colour schema already in place, and the icon is a "select anything" Regex using the existing title font: I thought that was a pretty decent image to capture the site.

I have some examples of how this should look.
<figure>
<figcaption>
An example of the iOS home screen icon:
</figcaption>

fullsizeoutput_1a1

</figure>

<figure>
<figcaption>
An example of the in-browser icon (in iOS Chrome):
</figcaption>

fullsizeoutput_19f

</figcaption>

<figure>
<figcaption>
A (very small, sorry) example of the Safari pinned tab icon.
</figcaption>

screen shot 2017-05-13 at 13 03 33

</figure>

### CODE REVIEW

**Comment by jonmagic** [comment]
This is so cool! I was wondering if it would be possible to:

* tighten the kerning a bit
* vertically align so that there is equal distance above and below the slashes
* increase the font weight ever so slightly

If not that's fine, but thought it was worth asking :)

**Comment by DanArthurGallagher** [comment]
@jonmagic
I made this in Google Drawings and just drew the characters in the font, so my answers are:
Kerning: I'm not sure, I think it's tied to the font but I can investigate. 
Vertical align: I will fix that.
Font-weight: I will try bolding it out, and fiddle with a few things. 
I'm in UTC+1 so I'll give this a bash in the morning and hopefully have something for you to review.

**Comment by DanArthurGallagher** [comment]
@jonmagic I've got commits locally with both of these icons in place, so let me know what you prefer:

<figure>
<figcaption>
The icon on the left is the centred icon, the icon on the right is centred with a bold font.
</figcaption>


icon comparison

</figure>

I'll push up the set with your preferred icon.

**Comment by DanArthurGallagher** [comment]
@jonmagic I've been adjusting to a new job and busy at home recently: I'll pick this up and get the merge completed in the next few days!

**Comment by DanArthurGallagher** [comment]
@jonmagic I've pulled in your icon changes and so this should be ready to merge in.

**Comment by jonmagic** [comment]
Sorry it took me so long to get to this! Changes are merged and the site has been updated :metal: You're [already listed as a contributor](https://github.com/jonmagic/scriptular/commit/9544a85dbdd8acd0141c70ab0f66eea769c5e42c) so no changes there :smile:

Thank you again :zap:

**Pull request merged**
